config/routes.rb
Rails.application.routes.draw do
   

  devise_for :users
  root 'users#index'
  resources :users
  resources :tracks  
  resources :comments

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # As we want everyone to be able to view our blog we don't need to set this default user.
    # We don't care about permissions for people who haven't logged in
    alias_action :edit, :update, :delete, :destroy, to: :modify

    user ||= User.new

    if user.admin?
      can :manage, :all
    elsif user.user?
      can [:create, :edit, :destroy], Track, user_id: user.id
      can [:create, :edit, :destroy], Comment, user_id: user.id
    else
     
    end
    can :read, :all
    can :modify, User, id: user.id
    # can [:new, :create], User
  end
end
    
    # can [:edit, :update], Post, user_id: user.id
    # can [:new, :create], Post


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :track 
belongs_to :user
end

app/models/track.rb
class Track < ActiveRecord::Base
belongs_to :user
has_many :comments

mount_uploader :song, SongUploader 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tracks
  has_many :comments, through: :tracks


  mount_uploader :image, UserImageUploader
   
  def admin?
    self.role == 'admin'
  end

  def user?
    self.role == 'user'
  end

  before_create :set_default_role

  private
  def set_default_role
    self.role = "user"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    binding.pry
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :image
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
before_action :authenticate_user!, only: [:new, :create, 
  :edit, :update, :destroy]
  authorize_resource

  def index
    @comments = Comment.all
  end

  def show
    @comments = Comment.find(params[:id])
    @comment = Comment.new 
  end

  def new
    @comment = Comment.new
  end

  def edit
     @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(comment_params)
      @comment.user_id = current_user.id 
      
    # if  @comment.save 
    #   redirect_to current_user_path
    # end 

     respond_to do |format|
      if @comment.save
        format.html { redirect_to comments_url, notice: 'Comment Submitted' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @track, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end 
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:feedback, :track_id, :user_id)
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
 
before_action :authenticate_user!, only: [:new, :create, 
  :edit, :update, :destroy]

  authorize_resource

  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find(params[:id])
    @comment = Comment.new 
  end

  def new
    @track = Track.new
  end

  def edit
     @track = Track.find(params[:id])
  end

  def create
    @track = Track.new(track_params)
    @track.user_id = current_user.id 
    if  @track.save 
      redirect_to track_path(@track)
    end 
  end


  def update
      @track = Track.find(params[:id])
    respond_to do |format|
     end 
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_track
      @track = Track.find(params[:id])
    end

    def track_params
      params.require(:track).permit(:title, :length, :song, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 

  before_action :authenticate_user!, except: [:show]
  authorize_resource

  def index
    @users = User.all   
  end

  def show
    @user = User.find(params[:id])
  end
  
  def new 
     @user = User.new
  end 

  def edit
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(user_params) 
     
     respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
      end
  end 

  def update 
   @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
   
 def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
 end 

 private
    
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :image, :about, :contact, :genre, :track_id)
    end
    
end 
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.haml
.comment_form 
  %ul
    %li
      = form_for(@comment) do |f|
        %li= "Enter Feedback "
        %li= f.label :feedback
        %li= f.text_field :feedback

        %li= f.label :track
        %li= f.collection_select(:track_id, Track.all, :id, :title )

        %li= f.submit 
        %li= link_to 'Back to Users', root_path

app/views/comments/edit.html.haml
= render 'form'

= link_to 'Show', @comment 
= link_to 'Back', comments_path

app/views/comments/index.html.haml
.table
  %thead
  %tr
  %thName
  .colspan
  %tbody
    -@comments.each do |comment|
      =comment.feedback
      =link_to 'Show', comment  
      =link_to 'Edit', edit_comment_path(comment)
      =link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }


=link_to 'New Comment', new_comment_path 

app/views/comments/new.html.haml
=render 'form'

app/views/comments/show.html.haml
.comment
  %p Feedback???
  =@comments.feedback
  

app/views/layouts/application.html.haml
%html
  %head
    %title A Music Site
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield :body || "<body>"
    %p.notice= notice
    %p.alert= alert
    = yield
    %header.header
      %h1= link_to 'Its A Music Site', users_path
      %ul.menu
        - if user_signed_in?
          %li= link_to('Logout', destroy_user_session_path, :method => :delete)
          %li= link_to('Edit Registration', edit_user_registration_path)
        - else
          %li= link_to('Login', new_user_session_path)
          %li
            = link_to 'New User', new_user_registration_path

app/views/tracks/_form.html.haml
.tracks_new
  = form_for(@track) do |f|
    %a= f.label :title
    %a= f.text_field :title
    %a= f.label :song
    %a= f.file_field :song
    %a= f.label :length
    %a= f.text_field :length
    = f.submit

app/views/tracks/edit.html.haml
= render 'form'

= link_to 'Show', @track
= link_to 'Back', tracks_path

app/views/tracks/index.html.haml
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @tracks.each do |track|
      %tr
        %td= track.title
        %td= link_to 'Show', track
        %td= link_to 'Edit', edit_track_path(track)
        %td= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Track', new_track_path

app/views/tracks/new.html.haml
= render 'form'

= link_to 'Back', tracks_path

app/views/tracks/show.html.haml
%p
  %strong User name:
  = @track.user.name
%p
  %strong Title:
  = @track.title
%p
  %strong length:
  = @track.length
%p
  = audio_tag @track.song, controls: true, class: 'song-player'
%p
  %strong Feedback:
  - @track.comments.each do |comment|
    = comment.feedback
%p
  = render 'comments/form'
  = link_to 'Edit', edit_track_path(@track)
  |
  \#{link_to 'Back', tracks_path}
%br/
= link_to 'New Track', new_track_path

app/views/users/edit.html.haml
.edit_profile
  = form_for(@user) do |f|
    = f.label :name
    = f.text_field :name
    %br/
    = f.label :image
    %br/
    = f.file_field :image
    %br/
    = f.label :about
    %br/
    = f.text_field :about
    %br/
    = f.label :contact
    %br/
    = f.text_field :contact
    %br/
    = f.label :genre
    %br/
    = f.text_field :genre
    %br/
    %li= link_to 'Manage Songs', tracks_path
    = f.submit
    = link_to 'Cancel', root_path
  %div

app/views/users/index.html.haml
%table
  %tbody
    - @users.each do |user|
      = link_to (image_tag user.image), user
  

app/views/users/new.html.haml
= form_for(@user) do |f|
  = f.label :name
  = f.text_field :name
  = f.label :image
  = f.file_field :image
  = f.label :about
  = f.text_field :about
  = f.label :contact
  = f.text_field :contact
  = f.label :genre
  = f.text_field :genre
  %p
    = f.submit 'Submit'
    = link_to 'Back to all Users', root_path

app/views/users/show.html.haml
= form_for(@user) do |f|
  = f.label :name
  = f.text_field :name
  = f.label :image
  = f.file_field :image
  = f.label :about
  = f.text_field :about
  = f.label :contact
  = f.text_field :contact
  = f.label :genre
  = f.text_field :genre
  %p
    = f.submit 'Submit'
    = link_to 'Back to all Users', root_path